Repository codebynao/8thavenue-api, pull requests merged in 2021-01, with the labels that each got.

#1 feat(cloudinary): Setup CDN, config:
  cloudbuild.yaml
  package-lock.json
  package.json
  src/config/cloudinary.js
Labels: feature

#5 feat: add CRUD category
  src/controllers/category.ts
  src/interfaces/category.ts
  src/models/Category.ts
  src/routes/category.ts
  src/server.ts
Labels: LGTM, feature

#7 feat: add crud photo with the upload to cloudinary
  package-lock.json
  package.json
  src/config/cloudinary.js
  src/controllers/photo.ts
  src/interfaces/photo.ts
  src/models/Photo.ts
  src/routes/photo.ts
  src/server.ts
Labels: feature, needs review

#9 feat: add/remove photo from a user
  src/controllers/photo.ts
Labels: LGTM, feature

#11 fix: add hasMoreResults to photos pagination
  src/controllers/photo.ts
Labels: LGTM, fix

#14 fix: update auth response + add route to get info of auth user
  src/controllers/auth.ts
  src/controllers/user.ts
  src/routes/user.ts
Labels: fix, needs review

#15 fix: remove password from user populated in photos
  src/controllers/photo.ts
Labels: LGTM, fix

#17 feat: improve and unify responses with errors
  package-lock.json
  package.json
  src/controllers/auth.ts
  src/controllers/category.ts
  src/controllers/photo.ts
  src/controllers/user.ts
Labels: LGTM, feature

#18 fix: parse nested comparators values
  src/utils/index.ts
Labels: fix, needs review

#19 feat: add labels to categories
  src/controllers/category.ts
  src/interfaces/category.ts
  src/models/Category.ts
  src/routes/category.ts
Labels: feature, needs review

#21 fix: handle specialties object ids
  src/controllers/user.ts
Labels: fix, needs review

#22 fix: force country object dot notation
  src/controllers/user.ts
Labels: LGTM, fix
